#### Ansible inventory.
resource "local_file" "ansible_inventory" {
  depends_on = [ module.app-vsi ]
  content = <<-DOC
all:
  hosts:
    db_host:
      ansible_host: "${data.ibm_is_instance.db-vsi.primary_network_interface[0].primary_ip[0].address}"
    app_host:
      ansible_host: "${data.ibm_is_instance.app-vsi.primary_network_interface[0].primary_ip[0].address}"
    DOC
  filename = "ansible/inventory.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "app_ansible_sapnwapp-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
SAP_SID: "${var.SAP_SID}"
SAP_ASCS_INSTANCE_NUMBER: "${var.SAP_ASCS_INSTANCE_NUMBER}"
SAP_CI_INSTANCE_NUMBER: "${var.SAP_CI_INSTANCE_NUMBER}"
SAP_MAIN_PASSWORD: "${var.SAP_MAIN_PASSWORD}"
db_host: "${module.db-vsi.PRIVATE-IP}"
db_hostname: "${var.DB_HOSTNAME}"
sap_profile: "${var.APP_PROFILE}"
...
    DOC
  filename = "ansible/sapnwapp-vars.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "app_ansible_sapnwascs-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
SAP_SID: "${var.SAP_SID}"
SAP_ASCS_INSTANCE_NUMBER: "${var.SAP_ASCS_INSTANCE_NUMBER}"
SAP_CI_INSTANCE_NUMBER: "${var.SAP_CI_INSTANCE_NUMBER}"
SAP_MAIN_PASSWORD: "${var.SAP_MAIN_PASSWORD}"
sap_profile: "${var.APP_PROFILE}"

#SAP Installation kit path
KIT_SAPCAR_FILE: "${var.KIT_SAPCAR_FILE}"
KIT_SWPM_FILE: "${var.KIT_SWPM_FILE}"
KIT_SAPEXE_FILE: "${var.KIT_SAPEXE_FILE}"
KIT_SAPEXEDB_FILE: "${var.KIT_SAPEXEDB_FILE}"
KIT_IGSEXE_FILE: "${var.KIT_IGSEXE_FILE}"
KIT_IGSHELPER_FILE: "${var.KIT_IGSHELPER_FILE}"
KIT_SAPHOSTAGENT_FILE: "${var.KIT_SAPHOSTAGENT_FILE}"
KIT_EXPORT_DIR: "${var.KIT_EXPORT_DIR}"
KIT_DB2CLIENT_DIR: "${var.KIT_DB2CLIENT_DIR}"
...
    DOC
  filename = "ansible/sapnwascs-vars.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "db_ansible_sapnwdb-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
SAP_SID: "${var.SAP_SID}"
sap_host: "${module.app-vsi.PRIVATE-IP}"
sap_hostname: "${var.APP_HOSTNAME}"
SAP_ASCS_INSTANCE_NUMBER: "${var.SAP_ASCS_INSTANCE_NUMBER}"
SAP_MAIN_PASSWORD: "${var.SAP_MAIN_PASSWORD}"
db_profile: "${var.DB_PROFILE}"

#SAP Installation kit path
KIT_SAPCAR_FILE: "${var.KIT_SAPCAR_FILE}"
KIT_SWPM_FILE: "${var.KIT_SWPM_FILE}"
KIT_SAPEXE_FILE: "${var.KIT_SAPEXE_FILE}"
KIT_SAPEXEDB_FILE: "${var.KIT_SAPEXEDB_FILE}"
KIT_SAPHOSTAGENT_FILE: "${var.KIT_SAPHOSTAGENT_FILE}"
KIT_EXPORT_DIR: "${var.KIT_EXPORT_DIR}"
KIT_DB2_DIR: "${var.KIT_DB2_DIR}"
KIT_DB2CLIENT_DIR: "${var.KIT_DB2CLIENT_DIR}"
...
    DOC
  filename = "ansible/sapnwdb-vars.yml"
}
