---
# - SAP Note:
#   - 405827 - Linux: Recommended file systems
# - https://www.ibm.com/docs/en/db2/11.5?topic=databases-recommended-file-systems

- name: Get the RAM size
  set_fact:
    app_ram: "{{ sap_profile.split('-')[1].split('x')[1] }}"

- name: Create a list for the IDs of the disks
  ansible.builtin.set_fact:
    disk_ids: "{{ [] }}"

- name: Get the disk for swap
  ansible.builtin.set_fact:
    swap_disk: "{{ device.key }}"
    disk_ids: "{{ disk_ids + [device.key]  }}"
  loop: "{{ lookup('ansible.builtin.dict', ansible_devices) }}"
  loop_control:
    loop_var: device
  when:
    - not device.value.partitions
    - not device.value.holders
    - device.value.size == swap_disk_size
    - 'device.key not in disk_ids'
    - not (swap_disk is defined and swap_disk | length > 0)

- name: Check if the required storage device for swap is found
  fail:
    msg: "Could not find a free {{ swap_disk_size }} storage device for swap"
  when:  swap_disk is not defined

- name: Create a volume group for swap
  lvg:
    vg: "{{ sap_sid|lower }}_swap_vg"
    pvs: "/dev/{{ swap_disk }}"
    pesize: "32"

- name: Get the disk for SAP instance
  ansible.builtin.set_fact:
    sap_disk: "{{ device.key }}"
    disk_ids: "{{ disk_ids + [device.key]  }}"
  loop: "{{ lookup('ansible.builtin.dict', ansible_devices) }}"
  loop_control:
    loop_var: device
  when:
    - not device.value.partitions
    - not device.value.holders
    - device.value.size == sap_disk_size
    - 'device.key not in disk_ids'
    - not (sap_disk is defined and sap_disk | length > 0)

- name: Check if the required storage device for SAP instance is found
  fail:
    msg: "Could not find a free {{ sap_disk_size }} storage device for SAP instance"
  when:  sap_disk is not defined

- name: Create a volume group for SAP instance
  lvg:
    vg: "{{ sap_sid|lower }}_app_vg"
    pvs: "/dev/{{ sap_disk }}"
    pesize: "32"

# SWAP sizing:
# - SAP notes: 
#   - 2369910 - SAP Software on Linux: General information (v17)
#   - 2578899 - SUSE Linux Enterprise Server 15: Installation Note (v44)
#   - 1597355 - Swap-space recommendation for Linux (v3)

- name: Get the swap logical volume size for RAM lower than 32 GB
  set_fact:
    swap_lv_size: "{{ app_ram | int * 2 }}g"
  when: app_ram | int < 32

- name: Get the swap logical volume size for RAM higher than 32 GB
  set_fact:
    swap_lv_size: "{{ item.size }}g"
  loop: "{{ swap_lv }}"
  when: (app_ram | int >= 32) and (app_ram | int >= item.ram_min) and (app_ram | int <= item.ram_min)

- name: Create a logical volume for swap
  lvol:
    vg: "{{ sap_sid|lower }}_swap_vg"
    lv: "{{ sap_sid|lower }}_swap_lv"
    size: "{{ swap_lv_size }}"

- name: Create a logical volume for /usr/sap
  lvol:
    vg: "{{ sap_sid|lower }}_app_vg"
    lv: "{{ sap_sid|lower }}_usrsap_lv"
    size: "{{ usrsap_lv_size }}"

- name: Create a logical volume for /usr/sap/{{ sap_sid|upper }}
  lvol:
    vg: "{{ sap_sid|lower }}_app_vg"
    lv: "{{ sap_sid|lower }}_sap_lv"
    size: "{{ sap_lv_size }}"

- name: Create a logical volume for /sapmnt/{{ sap_sid|upper }}
  lvol:
    vg: "{{ sap_sid|lower }}_app_vg"
    lv: "{{ sap_sid|lower }}_sapmnt_lv"
    size: "{{ sapmnt_lv_size }}"

- name: Create a logical volume for /usr/sap/trans
  lvol:
    vg: "{{ sap_sid|lower }}_app_vg"
    lv: "{{ sap_sid|lower }}_saptrans_lv"
    size: "{{ saptrans_lv_size }}" 

- name: Create a swap filesystem
  filesystem:
    fstype: swap
    dev: "/dev/{{ sap_sid|lower }}_swap_vg/{{ sap_sid|lower }}_swap_lv"

- name: Create filesystem for /usr/sap
  filesystem:
    fstype: ext4
    dev: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_usrsap_lv"

- name: Create filesystem for /usr/sap/{{ sap_sid|upper }}
  filesystem:
    fstype: ext4
    dev: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_sap_lv"

- name: Create filesystem for /sapmnt/{{ sap_sid|upper }}
  filesystem:
    fstype: ext4
    dev: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_sapmnt_lv"

- name: Create filesystem for /usr/sap/trans
  filesystem:
    fstype: ext4
    dev: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_saptrans_lv"

- name: Add swap device to /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^/dev/{{ sap_sid|lower }}_swap_vg/{{ sap_sid|lower }}_swap_lv"
    line: "/dev/{{ sap_sid|lower }}_swap_vg/{{ sap_sid|lower }}_swap_lv  swap  swap  defaults  0 0"

- name: Check the current swap size
  set_fact:
    sap_vm_swap: "{{ ansible_swaptotal_mb }}"

- name: Mount swap volume
  command: swapon -a
  when: sap_vm_swap == 0

- name: Mount /usr/sap and add it to /etc/fstab
  mount:
    path: "/usr/sap"
    src: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_usrsap_lv"
    fstype: ext4
    state: mounted

- name: Mount /usr/sap/{{ sap_sid|upper }} and add it to /etc/fstab
  mount:
    path: "/usr/sap/{{ sap_sid|upper }}"
    src: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_sap_lv"
    fstype: ext4
    state: mounted

- name: Mount /sapmnt/{{ sap_sid|upper }} and add it to /etc/fstab
  mount:
    path: "/sapmnt/{{ sap_sid|upper }}"
    src: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_sapmnt_lv"
    fstype: ext4
    state: mounted

- name: Mount /usr/sap/trans and add it to /etc/fstab
  mount:
    path: "/usr/sap/trans"
    src: "/dev/{{ sap_sid|lower }}_app_vg/{{ sap_sid|lower }}_saptrans_lv"
    fstype: ext4
    state: mounted
...
