---
# SAP Note:
# - 2570458 - DB6: Depooling report RUTPOADAPT fails with SQL -912 (v1)

- hosts: db_host
  gather_facts: yes
  vars: 
    db2_var: "DB2_AVOID_LOCK_ESCALATION"
    db2_var_newval: "TRUE"
  pre_tasks:
    - name: Import playbook variables
      include_vars: "sapnwdb-vars.yml"
  
  tasks:
    - name: Check if DB2 is installed
      stat:
        path: "/db2/db2{{ SAP_SID|lower }}/db2_software/bin/db2cli"
      register: install_db2status
      when: > 
            ansible_facts['os_family'] == "Suse" and ansible_facts['distribution_major_version'] == "15" 
            or ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

    - name: Check the value of DB2_AVOID_LOCK_ESCALATION variable
      shell: "su - db2{{ SAP_SID|lower }} -c 'db2set DB2_AVOID_LOCK_ESCALATION'"
      register: avoid_lk_esc
      when: install_db2status.stat is defined and install_db2status.stat.exists

    - name: SAP Note 2570458 - Reverting variable DB2_AVOID_LOCK_ESCALATION to TRUE
      import_role:
        name: sapdb2ops
        tasks_from: set_db2var
      when: avoid_lk_esc.stdout is defined and (avoid_lk_esc.stdout|upper) == 'FALSE'
...
